AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Weber Brain Cognito User Pool'

Parameters:
  UserPoolName:
    Type: String
    Default: WeberBrainUserPool
  AppClientName:
    Type: String
    Default: WeberBrainApp
  CognitoDomainPrefix:
    Type: String
    Default: weberbrain

Resources:
  WeberBrainUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

  WeberBrainUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Ref AppClientName
      GenerateSecret: false
      UserPoolId: !Ref WeberBrainUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      CallbackURLs:
        - http://localhost
      AllowedOAuthFlows:
        - implicit
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO

  WeberBrainUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomainPrefix
      UserPoolId: !Ref WeberBrainUserPool

Outputs:
  UserPoolId:
    Description: ID of the Cognito User Pool
    Value: !Ref WeberBrainUserPool
  UserPoolClientId:
    Description: ID of the Cognito User Pool Client
    Value: !Ref WeberBrainUserPoolClient
  CognitoDomain:
    Description: Cognito hosted UI domain
    Value: !Sub https://${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com
